stages:
- build
- test 
- sonarqube
- docker


build:
  stage: build
  script:
    - cd S3-ITProject
    - ./gradlew build -x test
    - ./gradlew.bat --stop 
test:
  stage: test
  script:
    - cd S3-ITProject
    - ./gradlew test
    - ./gradlew.bat --stop

sonarqube:
  image: gradle:jre11-slim
  variables:
    SONAR_USER_HOME: "${S3-ITProject}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${sonarqube}"
    paths:
      - .sonar/cache
  stage: sonarqube
  script:    
    - cd S3-ITProject    
    - ./gradlew sonarqube    
    - ./gradlew.bat --stop  
  allow_failure: true  
  only:
    - main

  # variables:
  #   SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache


docker:
    stage: docker
    script: 
      - docker-compose up
      - docker-compose down
