stages:
- build
- test 
- cypress
- sonarqube
- docker


build:
  stage: build
  script:
    - cd S3-ITProject
    - ./gradlew build -x test
    - ./gradlew.bat --stop 
test:
  stage: test
  script:
    - cd S3-ITProject
    - ./gradlew test
    - ./gradlew.bat --stop

cypress:
  image: cypress/browsers:node12.14.1-chrome85-ff81
  stage: test
  script:
    - cd s3-react-app
    # start the server in the background
    - npm run start:ci &
    # run Cypress tests
    - npx cypress run --browser chrome

sonarqube:
  image: gradle:jre11-slim
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  stage: sonarqube
  script:    
    - cd S3-ITProject    
    - ./gradlew sonarqube    
    - ./gradlew.bat --stop  
  allow_failure: true  
  only:
    - main

  # variables:
  #   SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache


docker:
    stage: docker
    script: 
      - docker-compose up
      - docker-compose down
