stages:
- build
- test 
- sonarqube


build:
  stage: build
  script:
    - cd S3-ITProject
    - ./gradlew build -x test
    - ./gradlew.bat --stop 
test:
  stage: test
  script:
    - cd S3-ITProject
    - ./gradlew test
    - ./gradlew.bat --stop

sonarqube:
  stage: sonarqube
  image: 
    gradle:jre11-slim  
  script:    
    - cd S3-ITProject    
    - ./gradlew sonarqube    
    - ./gradlew.bat --stop  
  allow_failure: true  
  only:
    - main
